server:
  port: ${PORT:10000}
eureka:
  instance:
    hostname: ${EUREKA_DOMAIN:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:10000/eureka/}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000