server:
  tomcat:
    uri-encoding: UTF-8
  port: 11111
spring:
  datasource:
    url: jdbc:mysql://11.11.11.101:3306/langchao?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: wave-service-user
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 11.11.11.103
    username: guest
    password: guest
    port: 5672
    virtual-host: /
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.langchao.waveserviceuser.mapper
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_empty
      db-type: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:666/eureka/
  instance:
    prefer-ip-address: true
    instance-id: wave-service-user
fdfs:
  pool:
    max-total: 200
    max-total-per-key: 50
    max-wait-millis: 5000
    testOnBorrow: false
  soTimeout: 1500
  connectTimeout: 600
  resHost: 11.11.11.104
  storagePort: 5000
  thumbImage:
    width: 150
    height: 150
  trackerList:
    - 11.11.11.104:22122
feign:
  hystrix:
    enabled: true
langchao:
  mq:
    queue: queue_langchao
    exchange: exchange_langchao
    routingKey: routing_langchao