server:
  port: 20000
spring:
  datasource:
    url: jdbc:mysql://11.11.11.101:3306/files?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: wave-service-filesystem
fdfs:
  pool:
    max-total: 200
    max-total-per-key: 50
    max-wait-millis: 5000
    testOnBorrow: false
  soTimeout: 1500
  connectTimeout: 600
  resHost: 11.11.11.104
  storagePort: 5000
  thumbImage:
    width: 150
    height: 150
  trackerList:
    - 11.11.11.104:22122
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.langchao.wavepo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_empty
      db-type: mysql