server:
  port: ${port:60000}
spring:
  datasource:
    url: jdbc:mysql://11.11.11.1001:3306/wave_media?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  application:
    name: wave-service-media
  rabbitmq:
    host: 11.11.11.103
    username: guest
    password: guest
    port: 5672
    virtual-host: /
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.langchao.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_empty
      db-type: mysql
langchao:
  upload-location: E:\video\
  ffmpeg-path: D:\ffmpeg\bin\ffmpeg.exe
  mq:
    exchange: langchao_mq_exchange
    queue: langchao_mq_queue
    routingKey: langchao_mq_routingKey
eureka:
  client:
    service-url:
      defaultZone: http://localhost:666/eureka/
  instance:
    prefer-ip-address: true
    instance-id: wave-service-media