server:
  port: ${port:50000}
spring:
  data:
    elasticsearch:
      cluster-name: elk
      cluster-nodes: 11.11.11.105:9300
  application:
    name: wave-service-search
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: wave-service-search